# -*- coding: utf-8 -*-
"""opcion2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bio8Zq2UyhdK_gR_mMNcs1kpqHgy5ksQ
"""

import tensorflow as tf
!pip install tensorflow
!pip install tensorflowjs

!node -v

!npm install @tensorflow/tfjs-node

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train.js
# const tf = require('@tensorflow/tfjs-node');
# 
# async function entrenar() {
# 
#   const celsius = tf.tensor1d([-40, -10, 0, 8, 15, 22, 38]);
#   const fahrenheit = tf.tensor1d([-40, 14, 32, 46, 59, 72, 100]);
# 
#   const modelo = tf.sequential();
#   modelo.add(tf.layers.dense({
#     units: 1,
#     inputShape: [1]
#   }));
# 
#   modelo.compile({
#     optimizer: tf.train.adam(0.1),
#     loss: 'meanSquaredError'
#   });
# 
#   console.log("Entrenando modelo...");
#   await modelo.fit(celsius, fahrenheit, { epochs: 100 });
# 
#   console.log("Modelo entrenado");
# 
#   await modelo.save('file://modelo_tfjs');
#   console.log("Modelo guardado en carpeta modelo_tfjs");
# }
# 
# entrenar();
#

!ls -l train.js

!node train.js

!ls

!ls modelo_tfjs